#define SMILEY_EYE_HEIGHT TOP_MARGIN
#define SMILEY_NOSE_HEIGHT SMILEY_EYE_HEIGHT + 1
#define SMILEY_MOUTH_HEIGHT SMILEY_NOSE_HEIGHT + 1
#define FROWNEY_EYE_HEIGHT TOP_MARGIN
#define FROWNEY_NOSE_HEIGHT FROWNEY_EYE_HEIGHT + 1
#define FROWNEY_MOUTH_HEIGHT FROWNEY_NOSE_HEIGHT + 1